### ISSUE TITLE
[Bug] (Latest version)

### ISSUE THREAD

**Issue by KimsFerdy** [Synthoid/substance-for-unity-extensions#3]
Unity Editor Crash of death forcing me to reimport all the libraries

**To Reproduce**
1. Install the Adobe Substances 3D from the Unity Asset Store
2. Install the latest Version of this github release
3. It will automatically crash itself

**Expected behavior**
Unity Crash while compiling the Editor dll of this plugin

**Desktop :**
 - OS: [e.g. Windows 10]
 - Unity Engine Version [e.g. `6 LTS`]
 - Substance 3D for Unity plugin version [e.g. 3.4.0]

**Comment by Synthoid** [comment]
I think Adobe has said that Unity 6 isn't supported yet, so this is likely an issue with the Substance DLL files. That said, I'm planning on testing the extensions package over the next week or so to bring it up to pairing with the latest plugin version.

**Comment by Synthoid** [comment]
I ran some tests over the past few days and I believe this is indeed an issue with the core Adobe plugin, not the extensions package.

Likely the crash occurs after installing because the extensions package has some `.sbsar` assets for the example scenes, while the core Adobe plugin has no substance assets. Since the core plugin will crash when it attempts to render substances, the crash occurs after the extensions package has been installed. Testing on pre-6 versions of Unity has things working as expected for me.

Going to close this issue since I'm pretty confident that this is a problem with the core Adobe plugin.
